version: "2.0"
nlu:
- intent: deny
  examples: |
    - مش صح
    - نو
    - مش مظبوط
    - لا
- intent: ask_for_avialable_schedule
  examples: |
    - أيه أفضل جدول ليا و انا شايل مواد
    - عايز اعرف المواد المتاحة ليا
    - عايز اعرف أفضل جدول متاح ليا
    - عايز أعرف ممكن أسجل مواد ايه
- intent: bot_challenge
  examples: |
    - هل أتحدث إلى روبوت؟
    - إلى من أتكلم؟
    - هل أنت إنسان؟
    - الذي هو معي؟
- intent: affirm
  examples: |
    - صح
    - اكيد
    - بالضبط
    - مظبوط
    - ايوا
    - اه
- intent: goodbye
  examples: |
    - شكرا لحضرتك
    - تمام
    - شكرا سلام
    - شكرا لحضرتك سلام
    - شكرا لحضرتك باي
    - اشطا
    - سلام
- intent: greet
  examples: |
    - مساء الخير
    - أهلا
    - طاب مسائك
    - السلام عليكم
    - هاي
    - أهلا انا
    - مرحبا
    - صباح الخير
- intent: ask_for_avialable_subject
  examples: |
    - طب ينفع اسجل [data structures](subject)
    - ممكن اسجل [math 1](subject)
    - أقدر اسجل مادة[image processing](subject)
    - أقدر اسجل مادة[machine learning](subject)
    - ينفع اسجل مادة [object oriented programming](subject)
    - ممكن اسجل [statistiscs and propabitity](subject)
    - أقدر اسجل مادة[statistics](subject)
    - أقدر اسجل مادة[structured programming](subject)
- intent: ask_for_major
  examples: |
    - عايز اعرف الاقسام
    - عايز اعرف ايه احسن تخصص
    - ايه احسن تخصص ليا؟
    - ممكن اسأل على الاقسام
    - اتخصص في ايه؟
    - ممكن اسأل على التخصصات
    - التخصصات
    - ايه الاقسام المتاحة
    - الاقسام
    - ايه احسن قسم ادخله؟
- intent: chitchat
  examples: |
    - اية لونك المفضل
    - انت ابن مين
    - ممكن تعرفي الساعة كام؟
    - محمد صلاح افضل ولا هالاند
    - الكرة
    - بتحب ميسي
    - انت اهلاوي ولا زملكاوي؟
    - بتشرب شاي
    - عندك كام سنة
    - طولك قد اية؟
    - ممكن تعرفني حالة الطقس النهاردة؟
    - انت ابن مين؟
    - مقاس رجلك كام
    - تقدر تقولي الساعة كام؟
    - اسمك اية؟
    - لابس اية
    - بشرب اية
    - انت عندك كام سنة؟
    - بتشرب اية؟
    - الزمالك
    - وزنك قداية
    - بتحب اية؟
    - بتشرب؟
    - انت مين؟
    - انت اهلاوي
    - انت جنسيتك اية
    - الساعة
    - بتحب مصر ؟
    - انا بحب الايام المشمسة في القاهرة
    - الجو عامل اية النهاردة؟
    - انت والدك اسمة اية
    - اسمك اية
    - بتحب البطيخ
    - الجو حر النهاردة
    - بتلعب ليج؟
    - كم عمرك؟
    - هل الطقس مشمس النهاردة؟
    - الساعة كام؟
    - من انت؟
    - عندك اسم؟
    - مين انت
- intent: student_id
  examples: |
    - [20220225](id)
    - [20210065](id)
    - [20200269](id)
    - [20120012](id)
    - [20200236](id)
    - [20210018](id)
    - [20220201](id)
    - [20220202](id)
    - [20240324](id)
    - [20210136](id)
    - [20200123](id)
    - [20240323](id)
    - [20160262](id)
    - [20220206](id)
    - [20210013](id)
    - [20200452](id)
    - [20180065](id)
    - [20210561](id)
    - [20220205](id)
    - [20210014](id)
    - [20200651](id)
    - [20230210](id)
    - [20220204](id)
    - [20230320](id)
    - [20200502](id)
    - [20230235](id)
    - [20160102](id)
    - [20210016](id)
    - [20160342](id)
    - [20210019](id)
    - [20210012](id)
    - [20160013](id)
    - [20200258](id)
    - [20160022](id)
    - [20160001](id)
    - [20200350](id)
    - [20200324](id)
    - [20190444](id)
    - [20230322](id)
    - [20230245](id)
    - [20240325](id)
    - [20220203](id)
